# This file was generated by GoReleaser. DO NOT EDIT.
cask "honey" do
  version "0.2.9"

  on_macos do
    on_intel do
      sha256 "ed2a4f7289a7196cad23619c06256f9c094e25f820da89693872f3637429d104"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "655d4986a002dbabcd204989c98a82886794fbbc15d7646d7fb7441caaa95f87"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "668e1692c32ec0532249de0c38a683cb69fc5ccba4913c0c326625e0075b7342"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7ea703965ff77c35762a4058843209151bb92b7349de4051c1a4d9bcf20201e7"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Linux_arm64.tar.gz"
    end
  end

  name "honey"
  desc "Search and operate on instances across GCP, AWS, Kubernetes, Consul, and Proxmox"
  homepage "https://github.com/shareed2k/honey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "honey"
  bash_completion "completions/honey.bash"
  fish_completion "completions/honey.fish"
  zsh_completion "completions/honey.zsh"

  # No zap stanza required

end
