# This file was generated by GoReleaser. DO NOT EDIT.
cask "honey" do
  version "0.2.8-pre3"

  on_macos do
    on_intel do
      sha256 "1e65021467b8783504b4fe3b167fe281a30eea2296a25b98fe9f5b95a8abce2e"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ec77f659572c268b1a6beb51daefe3bb311fc42ae52b5d251ce7684544aff65f"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "31fae8e01d6d28b5b7944d090af41f2d35de25feb968ba8bfc4dad8a4a40fe74"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "95968c4a5aa98c448d2c9610c1ae54587f35e2a8b6faa3aef12d3a076982d25c"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Linux_arm64.tar.gz"
    end
  end

  name "honey"
  desc "Search and operate on instances across GCP, AWS, Kubernetes, Consul, and Proxmox"
  homepage "https://github.com/shareed2k/honey"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "honey"
  bash_completion "completions/honey.bash"
  fish_completion "completions/honey.fish"
  zsh_completion "completions/honey.zsh"

  # No zap stanza required

end
