# This file was generated by GoReleaser. DO NOT EDIT.
cask "honey" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "d3426a633d8ffa6c85dffe22d262336a2a93b7235200a9cde88577c016d4c1e0"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2b2fa5eaae7ba713a8f2e248b1f6edbd57cc0cfa5b0410887650e924f1611382"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3d1c9e3554854fab314230558e27a6e8bffd9b0fd1629a57dcabad58269fcc7"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ddc381ad9806df617c42b845f8261beefb6ea45cdb9920319b2facef233b34a6"
      url "https://github.com/Shareed2k/honey/releases/download/v#{version}/honey_Linux_arm64.tar.gz"
    end
  end

  name "honey"
  desc "Search and operate on instances across GCP, AWS, Kubernetes, Consul, and Proxmox"
  homepage "https://github.com/shareed2k/honey"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "openssh",
      "tmux",
      "tun2proxy",
    ]

  binary "honey"
  bash_completion "completions/honey.bash"
  fish_completion "completions/honey.fish"
  zsh_completion "completions/honey.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/honey"]
    end
  end

  # No zap stanza required

end
