# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Honey < Formula
  desc "Search and operate on instances across GCP, AWS, Kubernetes, Consul, and Proxmox"
  homepage "https://github.com/shareed2k/honey"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Shareed2k/honey/releases/download/v0.2.4/honey_Darwin_x86_64.tar.gz"
      sha256 "fe9fe4ca326188a9b97c11ded03153c27f5d6f53f9803bd930145bc8f8592043"

      define_method(:install) do
        bin.install "honey"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Shareed2k/honey/releases/download/v0.2.4/honey_Darwin_arm64.tar.gz"
      sha256 "ea6569a249c2631088a0f1238b39522b4a86d7577ab218bb1f41856dd55fee55"

      define_method(:install) do
        bin.install "honey"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shareed2k/honey/releases/download/v0.2.4/honey_Linux_x86_64.tar.gz"
      sha256 "129d029f39f38a93c8710644a6af6a9a55508a803ba903044ab3235388287584"
      define_method(:install) do
        bin.install "honey"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Shareed2k/honey/releases/download/v0.2.4/honey_Linux_armv6.tar.gz"
      sha256 "07370f43022b521552ea78f99eaabf14dd421243d4a974eb65d101f8760a8fd8"
      define_method(:install) do
        bin.install "honey"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Shareed2k/honey/releases/download/v0.2.4/honey_Linux_arm64.tar.gz"
      sha256 "95252a58761bb57386b45109d1822e74a1cc6a0bdbc1c33965a045e997e32f46"
      define_method(:install) do
        bin.install "honey"
      end
    end
  end

  test do
    system "#{bin}/honey version"
  end
end
